version: "3"
services:
    command-app:
        container_name: command-app
        image: "mysql:5.6"
        ports:
            - "4306:3306"
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: "command_app"
